services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    networks:
      - red-app

  haproxy:
    image: haproxy:latest
    ports:
      - ${HAPROXY_HTTP_PORT:-80}:${HAPROXY_HTTP_PORT:-80}
      - ${HAPROXY_HTTPS_PORT:-443}:${HAPROXY_HTTPS_PORT:-443}
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.pem:/etc/haproxy/ssl/haproxy.pem
      - type: tmpfs
        target: /run/haproxy
    networks:
      - red-app

  app-web-1:
    image: romabreu/practica6-wa
    env_file:
      - .env
    ports:
      - ${SERVER_PORT_1:-8081}:${SERVER_PORT_1:-8081}
    environment:
      - NOMBRE_APP=${AMBIENTE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT_1:-8081}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
    restart: always
    networks:
      - red-app
    depends_on:
      - base-datos-app-web

  app-web-2:
    image: romabreu/practica6-wa
    env_file:
      - .env
    ports:
      - ${SERVER_PORT_2:-8082}:${SERVER_PORT_2:-8082}
    environment:
      - NOMBRE_APP=${AMBIENTE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT_2:-8082}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
    restart: always
    networks:
      - red-app
    depends_on:
      - base-datos-app-web

  app-web-3:
    image: romabreu/practica6-wa
    env_file:
      - .env
    ports:
      - ${SERVER_PORT_3:-8083}:${SERVER_PORT_3:-8083}
    environment:
      - NOMBRE_APP=${AMBIENTE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT_3:-8083}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
    restart: always
    networks:
      - red-app
    depends_on:
      - base-datos-app-web

  base-datos-app-web:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    networks:
      - red-app
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${PUERTO_PHPMYADMIN:-8084}:80
    environment:
      PMA_HOST: base-datos-app-web
      PMA_ARBITRARY: 1
    networks:
      - red-app
    depends_on:
      - base-datos-app-web

networks:
  red-app:
    driver: bridge
